Remove _typeobject workaround
It causes build failures on Python 3.14t:

```
  gcc -pthread -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -DNPY_TARGET_VERSION=NPY_1_19_API_VERSION -DNPY_NO_DEPRECATED_API=NPY_1_19_API_VERSION -I/tmp/build-env-81ran0co/lib/python3.14t/site-packages/numpy/_core/include -Icextern/astrometry.net -Iastropy_healpix -Icextern/numpy -I/tmp/build-env-81ran0co/include -I/opt/_internal/cpython-3.14.0-nogil/include/python3.14t -c astropy_healpix/_core.c -o build/temp.linux-x86_64-cpython-314t/astropy_healpix/_core.o -O2
  astropy_healpix/_core.c:33:8: error: redefinition of ‘struct _typeobject’
     33 | struct _typeobject {
        |        ^~~~~~~~~~~
  In file included from /opt/_internal/cpython-3.14.0-nogil/include/python3.14t/object.h:771,
                   from /opt/_internal/cpython-3.14.0-nogil/include/python3.14t/Python.h:81,
                   from astropy_healpix/_core.c:1:
  /opt/_internal/cpython-3.14.0-nogil/include/python3.14t/cpython/object.h:148:8: note: originally defined here
    148 | struct _typeobject {
        |        ^~~~~~~~~~~
  error: command '/opt/rh/gcc-toolset-14/root/usr/bin/gcc' failed with exit code 1
```