Fix bilinear interpolation of invalid values
Bilinear interpolation on invalid values (e.g. when calling
`reproject.reproject_from_healpix` where some values fall outside
the projection) should return NAN instead of printing to stderr
and raising an exception.

Before this patch, the [example in the docs for `ligo.skymap.plot.allsky`](https://lscsoft.docs.ligo.org/ligo.skymap/ligo/skymap/plot/allsky.html#example) was
failing with this output:

```
Invalid ring index: -537391105 4096
Invalid ring index: -537391105 4096
... repeated a few tens of thousands of times
Traceback (most recent call last):
  File "./test.py", line 34, in <module>
    ax.imshow_hpx(url, cmap='cylon')
  File "/Users/lpsinger/src/ligo.skymap/venv/lib/python3.7/site-packages/ligo/skymap/plot/allsky.py", line 401, in imshow_hpx
    nested=nested, field=field, smooth=smooth)
  File "/Users/lpsinger/src/ligo.skymap/venv/lib/python3.7/site-packages/ligo/skymap/plot/allsky.py", line 309, in _reproject_hpx
    field=field)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/reproject/healpix/high_level.py", line 73, in reproject_from_healpix
    order=order, nested=nested)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/reproject/healpix/core.py", line 84, in healpix_to_image
    data = hp.interpolate_bilinear_lonlat(lon_in, lat_in, healpix_data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy_healpix/high_level.py", line 201, in interpolate_bilinear_lonlat
    return interpolate_bilinear_lonlat(lon, lat, values, order=self.order)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy_healpix/core.py", line 413, in interpolate_bilinear_lonlat
    values = values[indices]
IndexError: index -2199022206976 is out of bounds for axis 1 with size 12582912
```

This was caused by a general lack of input validation and invalid
value propagation throughout the C library.

Fixes #77.